version: '3'

services:

  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
    networks:
      - layblar-platform

  dataservice:
    image: layblar/dataservice:1.0-${QUARKUS_MODE:-jvm}
    build:
      context: dataservice
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
    ports:
      - "8080:8080"
    networks:
      - layblar-platform

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meterdata
    networks:
      - layblar-platform

  simulator:
    image: layblar/smart-meter-simulator:1.0-${QUARKUS_MODE:-jvm}
    build:
      context: smart-meter-simulator
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
    networks:
      - layblar-platform

networks:
  layblar-platform:
    name: layblar-platform