openapi: 3.1.0
info:
  version: 1.0.0
  title: Layblar API
  termsOfService: https://example.com/terms/
  contact:
    email: contact@example.com
    url: http://example.com/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Test
tags:
  - name: SmartMeter
    description: Operations about Smart-Meter data.
components:
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: bearer
      bearerFormat: JWT
