version: '3'

services:

  layblar-device-library-service:
      container_name: layblar-device-library-service
      image: jfe7727/layblar-device-library-service:main
      depends_on:
        - mongodb-device
      environment:
        KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        QUARKUS_MONGODB_CONNECTION_STRING: ${MONODB_DEVICE_CON}
        MP_JWT_VERIFY_PUBLICKEY_LOCATION: file:///key/publicKey.pem
        MP_JWT_VERIFY_ISSUER: ${JWT_ISSUER}
        QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger-all-in-one:4317
      volumes:
        - ./publicKey.pem:/key/publicKey.pem
      ports:
        - 8085:8080
      networks:
        - layblar-platform

  mongodb-device:
    image: mongo
    mem_limit: 128m
    ports:
      - 27017:27017
    networks:
      - layblar-platform