version: '3'

services:

  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
    networks:
      - layblar-platform

  gateway:
    image: jfe7727/layblar-gateway:main
    depends_on:
      - postgres-gateway
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-gateway:5432/layblaruser
      QUARKUS_DATASOURCE_USERNAME: gateway
      QUARKUS_DATASOURCE_PASSWORD: gateway
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
    ports:
      - 8080:8080
    networks:
      - layblar-platform

  postgres-gateway:
    image: "postgres:10.5"
    mem_limit: 128m
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=gateway
      - POSTGRES_DB=layblaruser
    ports:
      - "5433:5432"
    networks:
      - layblar-platform

  layblar-smart-meter-service:
    container_name: layblar-smart-meter-service
    image: jfe7727/layblar-smartmeterservice:main
    depends_on:
      - timescaledb
      - rabbit
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://timescaledb:5432/meterdata
      QUARKUS_DATASOURCE_USERNAME: layblar
      QUARKUS_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8080"
    networks:
      - layblar-platform

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: layblar
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meterdata
    volumes:
      - ./TimeScaleDBSetup.sql:/docker-entrypoint-initdb.d/TimeScaleDBSetup.sql
    networks:
      - layblar-platform

  simulator:
    image: jfe7727/layblar-smart-meter-simulator:main
    depends_on:
      - rabbit
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
      QUARKKUS_HTTP_PORT: 8080
    ports:
      - "8088:8080"
    networks:
      - layblar-platform

networks:
  layblar-platform:
    name: layblar-platform
