version: '3'

include:
  # - gateway.yaml
  # - household-service.yaml
  # - smart-meter-service.yaml
  # - device-service.yaml
  - simulator.yaml
  # - kafka.yaml
  - rabbit.yaml

networks:
  layblar-platform:
    name: layblar-platform
