version: '3'

include:
  - gateway.yaml
  - household-service.yaml
  - smart-meter-service.yaml
  - simulator.yaml

services:

  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
    networks:
      - layblar-platform

networks:
  layblar-platform:
    name: layblar-platform
