version: '3'

services:
  gateway:
    image: jfe7727/layblar-gateway:main
    depends_on:
      - postgres-gateway
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-gateway:5432/layblaruser
      QUARKUS_DATASOURCE_USERNAME: ${GATEWAY_DB_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${GATEWAY_DB_PW}
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: file:///key/publicKey.pem
      SMALLRYE_JWT_SIGN_KEY_LOCATION: file:///key/privateKey.pem
      MP_JWT_VERIFY_ISSUER: ${JWT_ISSUER}
    volumes:
      - ./publicKey.pem:/key/publicKey.pem
      - ./privateKey.pem:/key/privateKey.pem
    ports:
      - 80:8080
    networks:
      - layblar-platform

  postgres-gateway:
    image: "debezium/postgres:16-alpine"
    mem_limit: 128m
    environment:
      - POSTGRES_USER=${GATEWAY_DB_USER}
      - POSTGRES_PASSWORD=${GATEWAY_DB_PW}
      - POSTGRES_DB=layblaruser
    ports:
      - "5433:5432"
    networks:
      - layblar-platform