version: '3'

services:

  layblar-household-service:
      container_name: layblar-household-service
      image: jfe7727/layblar-householdservice:main
      depends_on:
        - postgres-gateway
      environment:
        QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-household:5432/household
        QUARKUS_DATASOURCE_USERNAME: household
        QUARKUS_DATASOURCE_PASSWORD: household
        QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
        MP_JWT_VERIFY_PUBLICKEY_LOCATION: file:///key/publicKey.pem
        MP_JWT_VERIFY_ISSUER: makeThisASecretEnv
      volumes:
        - ./publicKey.pem:/key/publicKey.pem
      ports:
        - 8081:8080
      networks:
        - layblar-platform

  postgres-household:
    image: "postgres:10.5"
    mem_limit: 128m
    environment:
      - POSTGRES_USER=household
      - POSTGRES_PASSWORD=household
      - POSTGRES_DB=household
    ports:
      - "5434:5432"
    networks:
      - layblar-platform