version: '3'

services:

  zookeeper:
    image: quay.io/debezium/zookeeper:2.1
    ports:
     - 2181:2181
    networks:
     - layblar-platform

  kafka:
    image: quay.io/debezium/kafka:2.1
    ports:
     - 9092:9092
     - 9093:9093
    links:
     - zookeeper
    environment:
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
     - layblar-platform

  connect:
    image: quay.io/debezium/connect:2.1
    ports:
     - 8083:8083
    links:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
    - layblar-platform