version: '3'

services:

  layblar-project-service:
      container_name: layblar-project-service
      image: jfe7727/layblar-projectservice:main
      depends_on:
        - postgres-gateway
      environment:
        KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-project:5432/project
        QUARKUS_DATASOURCE_USERNAME: ${PROJECT_DB_USER}
        QUARKUS_DATASOURCE_PASSWORD: ${PROJECT_DB_PW}
        QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
        MP_JWT_VERIFY_PUBLICKEY_LOCATION: file:///key/publicKey.pem
        MP_JWT_VERIFY_ISSUER: ${JWT_ISSUER}
        QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger-all-in-one:4317
      volumes:
        - ./publicKey.pem:/key/publicKey.pem
      ports:
        - 8084:8080
      networks:
        - layblar-platform

  postgres-project:
    image: "debezium/postgres:16-alpine"
    mem_limit: 128m
    environment:
      - POSTGRES_USER=${PROJECT_DB_USER}
      - POSTGRES_PASSWORD=${PROJECT_DB_PW}
      - POSTGRES_DB=project
    ports:
      - "5435:5432"
    networks:
      - layblar-platform