global:
  scrape_interval: 15s
  external_labels:
    monitor: 'layblar-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'layblar'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['gateway:8080', 'layblar-household-service:8080', 'layblar-smart-meter-service:8080', 'layblar-project-service:8080' , 'layblar-device-library-service:8080']