version: '3'

services:

  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    hostname: rabbit
    restart: unless-stopped
    build:
      context: docker/
    ports:
      - "1883:1883"
      - "5672:5672"
      - "8883:8883"
      - "8090:15672"
      - "1885:15675"
    command: "/bin/bash -c \"rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_amqp1_0; rabbitmq-server\""
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/result/ca_certificate.pem:/key/ca_certificate.pem
      - ./rabbitmq/result/server_rabbit_certificate.pem:/key/server_rabbit_certificate.pem
      - ./rabbitmq/result/server_rabbit_key.pem:/key/server_rabbit_key.pem
    networks:
      - layblar-platform