version: '3'

services: 

  simulator:
    image: jfe7727/layblar-smart-meter-simulator:main
    depends_on:
      - rabbit
    environment:
      MP_MESSAGING_OUTGOING_METER_DATA_HOST: rabbit
      MP_MESSAGING_OUTGOING_METER_DATA_HOST: 1883
      QUARKKUS_HTTP_PORT: 8080
    ports:
      - "8088:8080"
    networks:
      - layblar-platform