version: '3'

services: 

  simulator:
    image: jfe7727/layblar-smart-meter-simulator:main
    depends_on:
      - rabbit
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
      QUARKKUS_HTTP_PORT: 8080
    ports:
      - "8088:8080"
    networks:
      - layblar-platform