version: '3'

services:

  layblar-smart-meter-service:
    container_name: layblar-smart-meter-service
    image: jfe7727/layblar-smartmeterservice:main
    depends_on:
      - timescaledb
      - rabbit
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://timescaledb:5432/meterdata
      QUARKUS_DATASOURCE_USERNAME: layblar
      QUARKUS_DATASOURCE_PASSWORD: password
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: file:///key/publicKey.pem
      MP_JWT_VERIFY_ISSUER: makeThisASecretEnv
    volumes:
      - ./publicKey.pem:/key/publicKey.pem
    ports:
      - "8082:8080"
    networks:
      - layblar-platform

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: layblar
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meterdata
    volumes:
      - ./TimeScaleDBSetup.sql:/docker-entrypoint-initdb.d/TimeScaleDBSetup.sql
    networks:
      - layblar-platform 