openapi: 3.1.0
info:
  version: 1.0.0
  title: Layblar Platform API
  contact:
    name: Layblar Documentation
    url: https://layblar.github.io/docs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://layblar.github.io/layblar_app/img/layblar_logo.png
  description: >
    # Introduction

    This is the API Documentation for the Layblar-Platform. 
servers:
  - url: http://{tenant}/api/v1
    variables:
      tenant:
        default: localhost:8080     
components:
  securitySchemes:
    jwt:
      type: http
      description: Authentication
      scheme: bearer
      bearerFormat: JWT
    none:
      type: http
      description: No Authentication
      scheme: No-Auth
