name: Generate API Documentation
on: 
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  generate-api-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gateway/gradlew

      - name: Run gradle build
        run: ./gateway/gradlew -p ./gateway build 

      - name: Check for changes in API documentation
        id: check-changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
            echo "::set-output name=changes::false"
          else
            echo "Changes detected."
            echo "::set-output name=changes::true"
          fi

      - name: Commit new OpenAPI YML and JSON
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'Yescob'
          git config --global user.email 'yescob@users.noreply.github.com'
          git commit -am "Automated API Documentation"
          git push
